# Generated by Django 4.2 on 2023-05-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.URLField(),
        ),
    ]
