# Generated by Django 4.2 on 2023-05-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_image_alter_furniture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='firstName',
        ),
    ]
